import { TOGGLE, MOVIES, SINGLE_MOVIE } from "./constants";

export const GET_MOVIES = `${MOVIES}`;
export const GET_MOVIES_SUCCESS = `${MOVIES}_SUCCESS`;
export const GET_MOVIES_FAILURE = `${MOVIES}_FAILURE`;

export const GET_SINGLE_MOVIE = `${SINGLE_MOVIE}`;
export const GET_SINGLE_MOVIE_SUCCESS = `${SINGLE_MOVIE}_SUCCESS`;
export const GET_SINGLE_MOVIE_FAILURE = `${SINGLE_MOVIE}_FAILURE`;

export const TOGGLE_FAVORITE = `${TOGGLE}_FAVORITE`;
